# Generated by Django 5.2 on 2025-09-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
    ]
